--------------------------------------------------------
--  File created - Thursday-July-28-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ASSIGNMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SGRS"."ASSIGNMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 30 START WITH 1900 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COURSE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SGRS"."COURSE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 10 START WITH 300 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GRADE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SGRS"."GRADE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 62 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOGIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SGRS"."LOGIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 2 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STAFF_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SGRS"."STAFF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STUDENT_BOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SGRS"."STUDENT_BOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 2 START WITH 140 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STUDENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SGRS"."STUDENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ASSIGNMENT
--------------------------------------------------------

  CREATE TABLE "SGRS"."ASSIGNMENT" 
   (	"ID" NUMBER, 
	"COURSE_ID" NUMBER, 
	"TOTAL_MARKS" FLOAT(126), 
	"PERCENTAGE" FLOAT(126), 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "SGRS"."COURSE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"STAFF_ID" NUMBER, 
	"TERM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRADE
--------------------------------------------------------

  CREATE TABLE "SGRS"."GRADE" 
   (	"ID" NUMBER(10,0), 
	"STUDENT_ID" NUMBER(10,0), 
	"ASSIGNMENT_ID" NUMBER(10,0), 
	"MARKS_OBTAINED" BINARY_DOUBLE, 
	"COURSE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "SGRS"."LOGIN" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"ROLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "SGRS"."STAFF" 
   (	"ID" NUMBER(10,0), 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"DEGREE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "SGRS"."STUDENT" 
   (	"ID" NUMBER(10,0), 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT_BOOK
--------------------------------------------------------

  CREATE TABLE "SGRS"."STUDENT_BOOK" 
   (	"ID" NUMBER(10,0), 
	"STUDENT_ID" NUMBER(10,0), 
	"STAFF_ID" NUMBER(10,0), 
	"COURSE_ID" NUMBER(10,0), 
	"TERM" VARCHAR2(50 BYTE), 
	"OVERALL_MARKS" BINARY_DOUBLE DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SGRS.ASSIGNMENT
SET DEFINE OFF;
Insert into SGRS.ASSIGNMENT (ID,COURSE_ID,TOTAL_MARKS,PERCENTAGE,NAME,DESCRIPTION) values (1540,220,100,10,'Assignment#1','Introduction');
commit;
REM INSERTING into SGRS.COURSE
SET DEFINE OFF;
Insert into SGRS.COURSE (ID,NAME,CODE,DESCRIPTION,STAFF_ID,TERM) values (1,'Leadership & Building','MGT','A Leadership Course',5,'Spring16');
Insert into SGRS.COURSE (ID,NAME,CODE,DESCRIPTION,STAFF_ID,TERM) values (2,'Information System Development','506','IT',5,'Spring2016');
Insert into SGRS.COURSE (ID,NAME,CODE,DESCRIPTION,STAFF_ID,TERM) values (220,'Mangerial Finance','MGF','Accounting and Finance Course',5,'Summer2016');
commit;
REM INSERTING into SGRS.GRADE
SET DEFINE OFF;
Insert into SGRS.GRADE (ID,STUDENT_ID,ASSIGNMENT_ID,MARKS_OBTAINED,COURSE_ID) values (48,2,1540,'50.0',220);
commit;
REM INSERTING into SGRS.LOGIN
SET DEFINE OFF;
Insert into SGRS.LOGIN (ID,USERNAME,PASSWORD,ROLE) values (1,'MarkW','Password1','Student');
Insert into SGRS.LOGIN (ID,USERNAME,PASSWORD,ROLE) values (2,'MeeliY','Password1','Student');
Insert into SGRS.LOGIN (ID,USERNAME,PASSWORD,ROLE) values (3,'HelloW','Password1','Student');
Insert into SGRS.LOGIN (ID,USERNAME,PASSWORD,ROLE) values (4,'YongxingS','Password1','Student');
Insert into SGRS.LOGIN (ID,USERNAME,PASSWORD,ROLE) values (5,'HS','HS','Professor');
Insert into SGRS.LOGIN (ID,USERNAME,PASSWORD,ROLE) values (6,'PrasanthiY','Password1','Student');
Insert into SGRS.LOGIN (ID,USERNAME,PASSWORD,ROLE) values (7,'CurtisS','Password1','Student');
Insert into SGRS.LOGIN (ID,USERNAME,PASSWORD,ROLE) values (8,'JelenaV','Password1','Professor');
commit;
REM INSERTING into SGRS.STAFF
SET DEFINE OFF;
Insert into SGRS.STAFF (ID,FIRSTNAME,LASTNAME,DEGREE) values (5,'Harshal','Shah','Software Developer');
Insert into SGRS.STAFF (ID,FIRSTNAME,LASTNAME,DEGREE) values (8,'Jelena','Vucetic','Ph.D.Electrical Engineering, Master''s C.S., and B.S. in Electrica');
commit;
REM INSERTING into SGRS.STUDENT
SET DEFINE OFF;
Insert into SGRS.STUDENT (ID,FIRSTNAME,LASTNAME,EMAIL,USERNAME) values (1,'Mark','Webb','mw@asd.com','MarkW');
Insert into SGRS.STUDENT (ID,FIRSTNAME,LASTNAME,EMAIL,USERNAME) values (2,'Meeli','Vyas','mv@asd.com','MeeliV');
Insert into SGRS.STUDENT (ID,FIRSTNAME,LASTNAME,EMAIL,USERNAME) values (3,'Hello','World','hw@as.com','HelloW');
Insert into SGRS.STUDENT (ID,FIRSTNAME,LASTNAME,EMAIL,USERNAME) values (4,'Yongxing','Sun','ys@sgrs.com','YongxingS');
Insert into SGRS.STUDENT (ID,FIRSTNAME,LASTNAME,EMAIL,USERNAME) values (6,'Prasanthi','Yerneni','py@sgrs.com','PrasanthiY');
Insert into SGRS.STUDENT (ID,FIRSTNAME,LASTNAME,EMAIL,USERNAME) values (7,'Curtis','Stroud','cs@sgrs.com','CurtisS');
commit;
REM INSERTING into SGRS.STUDENT_BOOK
SET DEFINE OFF;
Insert into SGRS.STUDENT_BOOK (ID,STUDENT_ID,STAFF_ID,COURSE_ID,TERM,OVERALL_MARKS) values (104,2,5,220,'a','5.0');
commit;
--------------------------------------------------------
--  DDL for Index USERNAME_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SGRS"."USERNAME_UNIQUE" ON "SGRS"."LOGIN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "SGRS"."USERNAME" ON "SGRS"."STUDENT" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "SGRS"."STAFF" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."STAFF" MODIFY ("DEGREE" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STAFF" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STAFF" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STAFF" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRADE
--------------------------------------------------------

  ALTER TABLE "SGRS"."GRADE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."GRADE" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."GRADE" MODIFY ("MARKS_OBTAINED" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."GRADE" MODIFY ("ASSIGNMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."GRADE" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."GRADE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "SGRS"."COURSE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."COURSE" MODIFY ("TERM" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."COURSE" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."COURSE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."COURSE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."COURSE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."COURSE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "SGRS"."LOGIN" ADD CONSTRAINT "USERNAME_UNIQUE" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."LOGIN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."LOGIN" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."LOGIN" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."LOGIN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "SGRS"."ASSIGNMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."ASSIGNMENT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."ASSIGNMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."ASSIGNMENT" MODIFY ("PERCENTAGE" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."ASSIGNMENT" MODIFY ("TOTAL_MARKS" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."ASSIGNMENT" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."ASSIGNMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT_BOOK
--------------------------------------------------------

  ALTER TABLE "SGRS"."STUDENT_BOOK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."STUDENT_BOOK" MODIFY ("OVERALL_MARKS" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT_BOOK" MODIFY ("TERM" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT_BOOK" MODIFY ("COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT_BOOK" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT_BOOK" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT_BOOK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "SGRS"."STUDENT" ADD CONSTRAINT "USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."STUDENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SGRS"."STUDENT" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SGRS"."STUDENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "SGRS"."ASSIGNMENT" ADD CONSTRAINT "ASSIGNMEN_FK" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "SGRS"."COURSE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "SGRS"."COURSE" ADD CONSTRAINT "STAFF_ID_FK" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SGRS"."STAFF" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRADE
--------------------------------------------------------

  ALTER TABLE "SGRS"."GRADE" ADD CONSTRAINT "GRADE_ASSIGNMENTID_FK" FOREIGN KEY ("ASSIGNMENT_ID")
	  REFERENCES "SGRS"."ASSIGNMENT" ("ID") ENABLE;
  ALTER TABLE "SGRS"."GRADE" ADD CONSTRAINT "GRADE_COURSEID_FK" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "SGRS"."COURSE" ("ID") ENABLE;
  ALTER TABLE "SGRS"."GRADE" ADD CONSTRAINT "GRADE_STUDENTID_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SGRS"."STUDENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "SGRS"."STAFF" ADD CONSTRAINT "STAFF_FK" FOREIGN KEY ("ID")
	  REFERENCES "SGRS"."LOGIN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "SGRS"."STUDENT" ADD CONSTRAINT "STUDENT_FK" FOREIGN KEY ("ID")
	  REFERENCES "SGRS"."LOGIN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT_BOOK
--------------------------------------------------------

  ALTER TABLE "SGRS"."STUDENT_BOOK" ADD CONSTRAINT "STUDENT_BOOK_COURSEID_FK" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "SGRS"."COURSE" ("ID") ENABLE;
  ALTER TABLE "SGRS"."STUDENT_BOOK" ADD CONSTRAINT "STUDENT_BOOK_STAFFID_FK" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SGRS"."STAFF" ("ID") ENABLE;
  ALTER TABLE "SGRS"."STUDENT_BOOK" ADD CONSTRAINT "STUDENT_BOOK_STUDENTID_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SGRS"."STUDENT" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ASSIGNMENT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."ASSIGNMENT_SEQ_TR" 
 BEFORE INSERT ON ASSIGNMENT FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN
 SELECT ASSIGNMENT_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "SGRS"."ASSIGNMENT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ASSIGNMENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."ASSIGNMENT_TRIGGER" BEFORE INSERT ON ASSIGNMENT FOR EACH ROW
BEGIN
  SELECT ASSIGNMENT_SEQ.nextval INTO :new.ID FROM dual;
END;
/
ALTER TRIGGER "SGRS"."ASSIGNMENT_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COURSE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."COURSE_SEQ_TR" 
 BEFORE INSERT ON COURSE FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN
 SELECT COURSE_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "SGRS"."COURSE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COURSE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."COURSE_TRIGGER" BEFORE INSERT ON COURSE FOR EACH ROW
BEGIN
  SELECT COURSE_SEQ.nextval INTO :new.ID FROM dual;
END;
/
ALTER TRIGGER "SGRS"."COURSE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GRADE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."GRADE_SEQ_TR" 
 BEFORE INSERT ON GRADE FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN
 SELECT GRADE_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "SGRS"."GRADE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOGIN_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."LOGIN_SEQ_TR" 
 BEFORE INSERT ON LOGIN FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN
 SELECT LOGIN_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "SGRS"."LOGIN_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STAFF_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."STAFF_SEQ_TR" 
 BEFORE INSERT ON STAFF FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN
 SELECT STAFF_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "SGRS"."STAFF_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STUDENT_BOOK_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."STUDENT_BOOK_SEQ_TR" 
 BEFORE INSERT ON STUDENT_BOOK FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN
 SELECT STUDENT_BOOK_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "SGRS"."STUDENT_BOOK_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STUDENT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SGRS"."STUDENT_SEQ_TR" 
 BEFORE INSERT ON STUDENT FOR EACH ROW
  WHEN (NEW.ID IS NULL) BEGIN
 SELECT STUDENT_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "SGRS"."STUDENT_SEQ_TR" ENABLE;
